//! [`StixId`](crate::core::StixId) JSON string serialization.
//!
//! Deserialize failures are tagged so [`crate::ParseError`] can recover
//! [`StixIdError`](crate::core::StixIdError) without Display-string matching
//! (same approach as [`crate::model::serde_error`] for `ModelError`). The tagged
//! payload carries the rejected id, so recovery replays [`StixId::parse`] and
//! reproduces the original error, including the `uuid` crate's detail.
//!
//! Typed-ID conversion (`created_by_ref` and the other typed reference
//! properties) is tagged separately: its payload carries the expected and found
//! type names, which is everything
//! [`StixIdError::TypeMismatch`](crate::core::StixIdError::TypeMismatch) holds.

use crate::core::{StixId, StixIdError, StixObjectKind};

/// Prefix embedded in serde custom messages.
const TAG: &str = "\u{001e}rstix-stix-id\u{001e}";

/// Prefix embedded in serde custom messages for typed-ID conversion failures.
const TYPED_TAG: &str = "\u{001e}rstix-typed-id\u{001e}";

/// Longest rejected id echoed into the tagged payload. Ids that fail
/// [`StixId::parse`] are short in practice, and the cap keeps a hostile document
/// from inflating error strings by the length of its own input. Longer ids fall
/// back to an untagged message and surface as [`crate::ParseError::Json`].
const MAX_TAGGED_ID_LEN: usize = 256;

fn encode_for_serde(raw: &str, err: &StixIdError) -> String {
    if raw.len() > MAX_TAGGED_ID_LEN {
        return err.to_string();
    }
    let payload = serde_json::to_string(raw).expect("json string encoding cannot fail");
    format!("{TAG}{payload}{TAG}{err}")
}

fn decode_from_serde(message: &str) -> Option<StixIdError> {
    let rest = message.strip_prefix(TAG)?;
    let json_end = rest.find(TAG)?;
    let raw: String = serde_json::from_str(&rest[..json_end]).ok()?;
    StixId::parse(&raw).err()
}

/// Tag a typed-ID conversion failure, as generated by
/// [`define_typed_id!`](crate::core::id).
///
/// [`StixIdError::TypeMismatch`] holds the expected type as a `&'static str`, so
/// recovery cannot allocate one. It does not need to: the expected type is one of
/// the macro's literals, which means [`StixObjectKind`] already owns the identical
/// `&'static str` and recovery can look it up.
pub(crate) fn encode_type_mismatch_for_serde(err: &StixIdError) -> String {
    let StixIdError::TypeMismatch { expected, found } = err else {
        return err.to_string();
    };
    if found.len() > MAX_TAGGED_ID_LEN {
        return err.to_string();
    }
    let payload = serde_json::to_string(&[*expected, found.as_str()])
        .expect("json string encoding cannot fail");
    format!("{TYPED_TAG}{payload}{TYPED_TAG}{err}")
}

fn decode_type_mismatch_from_serde(message: &str) -> Option<StixIdError> {
    let rest = message.strip_prefix(TYPED_TAG)?;
    let payload_end = rest.find(TYPED_TAG)?;
    let [expected, found] = serde_json::from_str::<[String; 2]>(&rest[..payload_end]).ok()?;
    let expected = static_type_name(&expected)?;
    if expected == found {
        return None;
    }
    Some(StixIdError::TypeMismatch { expected, found })
}

/// Resolve a decoded type name to the matching `&'static str`, so a forged or
/// unrecognized name yields no recovery instead of a fabricated error.
fn static_type_name(value: &str) -> Option<&'static str> {
    let name = StixObjectKind::from_type_str(value)?.as_str();
    (name == value).then_some(name)
}

/// Recover a [`StixIdError`] from a serde/`serde_json` error message when tagged.
pub(crate) fn stix_id_error_from_serde_message(message: &str) -> Option<StixIdError> {
    decode_from_serde(message).or_else(|| decode_type_mismatch_from_serde(message))
}

impl serde::Serialize for StixId {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> serde::Deserialize<'de> for StixId {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let raw = <String as serde::Deserialize>::deserialize(deserializer)?;
        Self::parse(&raw).map_err(|err| serde::de::Error::custom(encode_for_serde(&raw, &err)))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::IdentityId;

    fn parse_error(raw: &str) -> StixIdError {
        StixId::parse(raw).expect_err("id must be rejected")
    }

    #[test]
    fn tagged_roundtrip_reproduces_the_original_error() {
        for raw in [
            "malware--deadbeef",
            "malware--1121ffbc-364f-857a-9987-92fbcff24ab",
            "no-delimiter",
            "--0c7b5b88-8ff7-4a4d-aa9d-feb398cd0061",
        ] {
            let err = parse_error(raw);
            let recovered =
                decode_from_serde(&encode_for_serde(raw, &err)).expect("tagged message decodes");
            assert_eq!(recovered, err, "recovered error must match original: {raw}");
            assert_eq!(
                recovered.to_string(),
                err.to_string(),
                "recovered detail must match original: {raw}"
            );
        }
    }

    #[test]
    fn recovered_uuid_detail_describes_the_rejected_id() {
        let short = parse_error("malware--deadbeef");
        let truncated = parse_error("malware--1121ffbc-364f-857a-9987-92fbcff24ab");
        // A fixed stand-in cannot describe either id: recovery must not substitute one.
        let stand_in = parse_error("x--not-a-uuid");
        assert_ne!(
            short.to_string(),
            truncated.to_string(),
            "distinct malformed ids must yield distinct detail"
        );
        assert_ne!(stand_in.to_string(), truncated.to_string());
        assert_ne!(stand_in.to_string(), short.to_string());
        let recovered = decode_from_serde(&encode_for_serde(
            "malware--1121ffbc-364f-857a-9987-92fbcff24ab",
            &truncated,
        ))
        .expect("tagged message decodes");
        assert_eq!(recovered.to_string(), truncated.to_string());
    }

    #[test]
    fn deserialize_invalid_uuid_is_recoverable_from_serde_message() {
        let err = serde_json::from_str::<StixId>("\"malware--deadbeef\"").expect_err("must fail");
        let recovered = stix_id_error_from_serde_message(&err.to_string()).expect("tagged");
        assert_eq!(recovered, parse_error("malware--deadbeef"));
    }

    #[test]
    fn oversized_id_is_not_tagged() {
        let raw = format!("malware--{}", "a".repeat(MAX_TAGGED_ID_LEN));
        let err = parse_error(&raw);
        let message = encode_for_serde(&raw, &err);
        assert!(!message.starts_with(TAG), "oversized id must not be tagged");
        assert_eq!(decode_from_serde(&message), None);
    }

    #[test]
    fn typed_id_mismatch_roundtrips_through_the_serde_boundary() {
        let err = IdentityId::from_stix_id(
            StixId::parse("malware--0c7b5b88-8ff7-4a4d-aa9d-feb398cd0061").expect("valid id"),
        )
        .expect_err("wrong type must be rejected");
        let recovered = decode_type_mismatch_from_serde(&encode_type_mismatch_for_serde(&err))
            .expect("tagged message decodes");
        assert_eq!(recovered, err);
        assert_eq!(recovered.to_string(), err.to_string());
    }

    #[test]
    fn typed_id_mismatch_is_recoverable_from_the_deserializer() {
        let err =
            serde_json::from_str::<IdentityId>("\"malware--0c7b5b88-8ff7-4a4d-aa9d-feb398cd0061\"")
                .expect_err("wrong type must be rejected");
        let recovered = stix_id_error_from_serde_message(&err.to_string()).expect("tagged");
        assert_eq!(
            recovered,
            StixIdError::TypeMismatch {
                expected: "identity",
                found: "malware".to_owned(),
            }
        );
    }

    #[test]
    fn typed_id_expected_resolves_across_object_classes() {
        // The expected type is a `define_typed_id!` literal, so every class the
        // macro covers must resolve back to the registry's `&'static str`.
        for name in ["identity", "file", "relationship", "marking-definition"] {
            assert_eq!(static_type_name(name), Some(name));
        }
        for name in ["x-custom-type", "IDENTITY", "", "identity "] {
            assert_eq!(static_type_name(name), None, "must not resolve: {name}");
        }
    }

    #[test]
    fn oversized_found_type_is_not_tagged() {
        let err = StixIdError::TypeMismatch {
            expected: "identity",
            found: "a".repeat(MAX_TAGGED_ID_LEN + 1),
        };
        let message = encode_type_mismatch_for_serde(&err);
        assert!(!message.starts_with(TYPED_TAG));
        assert_eq!(decode_type_mismatch_from_serde(&message), None);
    }

    #[test]
    fn forged_typed_id_messages_do_not_recover() {
        for message in [
            format!("{TYPED_TAG}[\"x-forged\",\"malware\"]{TYPED_TAG}forged"),
            format!("{TYPED_TAG}[\"identity\",\"identity\"]{TYPED_TAG}not a mismatch"),
            format!("{TYPED_TAG}[\"identity\"]{TYPED_TAG}short payload"),
            format!("{TYPED_TAG}not-json{TYPED_TAG}bad payload"),
            format!("invalid value {TYPED_TAG}[\"identity\",\"malware\"]{TYPED_TAG}not at start"),
        ] {
            assert_eq!(
                decode_type_mismatch_from_serde(&message),
                None,
                "must not recover from: {message}"
            );
        }
    }

    #[test]
    fn untagged_or_forged_messages_do_not_recover() {
        let forged = format!("invalid type: string {TAG}\"malware--deadbeef\"{TAG}forged");
        for message in [
            "invalid type: string".to_owned(),
            String::new(),
            TAG.to_owned(),
            forged,
            format!("{TAG}\"malware--0c7b5b88-8ff7-4a4d-aa9d-feb398cd0061\"{TAG}valid id"),
            format!("{TAG}not-json{TAG}bad payload"),
        ] {
            assert_eq!(
                decode_from_serde(&message),
                None,
                "must not recover from: {message}"
            );
        }
    }
}
